### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'axis'

### ISSUE THREAD

**Issue by easyfcn** [j1a0m0e4sNTU/3dgcn#2]
dear，when add the -output in the train.sh or test.sh, I meet the problem. Could you help me? Thanks.

epoch   1 step  1000 | avg loss: 1.747 | miou(c): 0.440 | miou(i): 0.563
 epoch   1 step  2000 | avg loss: 1.232 | miou(c): 0.498 | miou(i): 0.631
 epoch   1 step  3000 | avg loss: 1.001 | miou(c): 0.532 | miou(i): 0.663
Traceback (most recent call last):
  File "main.py", line 67, in <module>
    main()
  File "main.py", line 56, in main
    manager.train(train_loader, test_loader)
  File "=/Graph/3dgcn-master/segmentation/manager.py", line 118, in train
    test_loss, test_table_str = self.test(test_data, self.out_dir)
  File "/Graph/3dgcn-master/segmentation/manager.py", line 151, in test
    self.save_visualizations(out_dir, cat_name, obj_ids, points, labels, pred)
  File "/Graph/3dgcn-master/segmentation/manager.py", line 81, in save_visualizations
    visualize(point, label, gt_fig_name)
  File "/Graph/3dgcn-master/segmentation/visualize.py", line 26, in visualize
    ax.axis('off')
AttributeError: 'NoneType' object has no attribute 'axis'

**Comment by chih-hao-lin** [comment]
Hi, I've checked the code and did not reproduce the error you mentioned,
I think it might be caused by the version of "matplotlib" package.
BTW, mine is "3.2.1"

**Comment by easyfcn** [comment]
dear,

Thank you for answering my question. My problem was solved!
Thank you once again!
